version: '3'
services:
  php:
    image: php:8.2-apache
    volumes:
      - ~/.composer/cache:/root/.composer/cache:delegated
      - ./:/var/www/html:delegated
    ports:
      - '8000:80'
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/web